# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 793)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ToolBar/Bilder/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.infoTableView = QtWidgets.QTableView(self.groupBox_3)
        self.infoTableView.setEnabled(True)
        self.infoTableView.setMinimumSize(QtCore.QSize(400, 200))
        self.infoTableView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.infoTableView.setLineWidth(1)
        self.infoTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.infoTableView.setDragDropOverwriteMode(False)
        self.infoTableView.setAlternatingRowColors(True)
        self.infoTableView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.infoTableView.setShowGrid(False)
        self.infoTableView.setWordWrap(False)
        self.infoTableView.setCornerButtonEnabled(False)
        self.infoTableView.setObjectName("infoTableView")
        self.infoTableView.horizontalHeader().setVisible(True)
        self.infoTableView.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.infoTableView)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listView_kategorien = QtWidgets.QListView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_kategorien.sizePolicy().hasHeightForWidth())
        self.listView_kategorien.setSizePolicy(sizePolicy)
        self.listView_kategorien.setMinimumSize(QtCore.QSize(100, 0))
        self.listView_kategorien.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listView_kategorien.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_kategorien.setProperty("showDropIndicator", False)
        self.listView_kategorien.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listView_kategorien.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView_kategorien.setObjectName("listView_kategorien")
        self.horizontalLayout_2.addWidget(self.listView_kategorien)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listView_regeln = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_regeln.sizePolicy().hasHeightForWidth())
        self.listView_regeln.setSizePolicy(sizePolicy)
        self.listView_regeln.setMinimumSize(QtCore.QSize(100, 0))
        self.listView_regeln.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listView_regeln.setObjectName("listView_regeln")
        self.verticalLayout.addWidget(self.listView_regeln)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listView_regel_und = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_regel_und.sizePolicy().hasHeightForWidth())
        self.listView_regel_und.setSizePolicy(sizePolicy)
        self.listView_regel_und.setMinimumSize(QtCore.QSize(100, 0))
        self.listView_regel_und.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listView_regel_und.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listView_regel_und.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_regel_und.setProperty("showDropIndicator", False)
        self.listView_regel_und.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView_regel_und.setObjectName("listView_regel_und")
        self.verticalLayout_2.addWidget(self.listView_regel_und)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.listView_regeln_oder = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_regeln_oder.sizePolicy().hasHeightForWidth())
        self.listView_regeln_oder.setSizePolicy(sizePolicy)
        self.listView_regeln_oder.setMinimumSize(QtCore.QSize(100, 0))
        self.listView_regeln_oder.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listView_regeln_oder.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_regeln_oder.setProperty("showDropIndicator", False)
        self.listView_regeln_oder.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView_regeln_oder.setObjectName("listView_regeln_oder")
        self.verticalLayout_3.addWidget(self.listView_regeln_oder)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.listView_regeln_nicht = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_regeln_nicht.sizePolicy().hasHeightForWidth())
        self.listView_regeln_nicht.setSizePolicy(sizePolicy)
        self.listView_regeln_nicht.setMinimumSize(QtCore.QSize(100, 0))
        self.listView_regeln_nicht.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listView_regeln_nicht.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_regeln_nicht.setProperty("showDropIndicator", False)
        self.listView_regeln_nicht.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView_regeln_nicht.setObjectName("listView_regeln_nicht")
        self.verticalLayout_4.addWidget(self.listView_regeln_nicht)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 23))
        self.menubar.setObjectName("menubar")
        self.menuRohdaten_laden = QtWidgets.QMenu(self.menubar)
        self.menuRohdaten_laden.setObjectName("menuRohdaten_laden")
        self.menuRegeln = QtWidgets.QMenu(self.menubar)
        self.menuRegeln.setObjectName("menuRegeln")
        self.menuHilfe = QtWidgets.QMenu(self.menubar)
        self.menuHilfe.setObjectName("menuHilfe")
        self.menuKategorie = QtWidgets.QMenu(self.menubar)
        self.menuKategorie.setObjectName("menuKategorie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNeue_Kategorie = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ToolBar/Bilder/list-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNeue_Kategorie.setIcon(icon1)
        self.actionNeue_Kategorie.setObjectName("actionNeue_Kategorie")
        self.actionRohdaten_laden = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ToolBar/Bilder/document-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRohdaten_laden.setIcon(icon2)
        self.actionRohdaten_laden.setObjectName("actionRohdaten_laden")
        self.actionExcel_exportieren = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ToolBar/Bilder/document-save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExcel_exportieren.setIcon(icon3)
        self.actionExcel_exportieren.setObjectName("actionExcel_exportieren")
        self.actionNeue_Regel = QtWidgets.QAction(MainWindow)
        self.actionNeue_Regel.setIcon(icon1)
        self.actionNeue_Regel.setObjectName("actionNeue_Regel")
        self.actionRegeln_speichern = QtWidgets.QAction(MainWindow)
        self.actionRegeln_speichern.setIcon(icon3)
        self.actionRegeln_speichern.setObjectName("actionRegeln_speichern")
        self.actionRegel_laden = QtWidgets.QAction(MainWindow)
        self.actionRegel_laden.setIcon(icon2)
        self.actionRegel_laden.setObjectName("actionRegel_laden")
        self.actionKategorien_l_schen = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ToolBar/Bilder/list-remove-all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKategorien_l_schen.setIcon(icon4)
        self.actionKategorien_l_schen.setObjectName("actionKategorien_l_schen")
        self.actionRegelExcel_exportieren = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ToolBar/Bilder/application-vnd.openxmlformats-officedocument.spreadsheetml.sheet.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegelExcel_exportieren.setIcon(icon5)
        self.actionRegelExcel_exportieren.setObjectName("actionRegelExcel_exportieren")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ToolBar/Bilder/application-exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon6)
        self.action_Exit.setObjectName("action_Exit")
        self.action_uber = QtWidgets.QAction(MainWindow)
        self.action_uber.setObjectName("action_uber")
        self.actionNeue_Bedingung = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ToolBar/Bilder/resource-calendar-insert.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNeue_Bedingung.setIcon(icon7)
        self.actionNeue_Bedingung.setObjectName("actionNeue_Bedingung")
        self.actionRegeln_loeschen = QtWidgets.QAction(MainWindow)
        self.actionRegeln_loeschen.setIcon(icon4)
        self.actionRegeln_loeschen.setObjectName("actionRegeln_loeschen")
        self.menuRohdaten_laden.addAction(self.actionRohdaten_laden)
        self.menuRohdaten_laden.addSeparator()
        self.menuRohdaten_laden.addAction(self.actionExcel_exportieren)
        self.menuRohdaten_laden.addSeparator()
        self.menuRohdaten_laden.addAction(self.action_Exit)
        self.menuRegeln.addAction(self.actionNeue_Regel)
        self.menuRegeln.addAction(self.actionNeue_Bedingung)
        self.menuRegeln.addAction(self.actionRegeln_loeschen)
        self.menuRegeln.addSeparator()
        self.menuRegeln.addAction(self.actionRegeln_speichern)
        self.menuRegeln.addAction(self.actionRegel_laden)
        self.menuRegeln.addSeparator()
        self.menuRegeln.addAction(self.actionRegelExcel_exportieren)
        self.menuHilfe.addAction(self.action_uber)
        self.menuKategorie.addAction(self.actionNeue_Kategorie)
        self.menuKategorie.addAction(self.actionKategorien_l_schen)
        self.menubar.addAction(self.menuRohdaten_laden.menuAction())
        self.menubar.addAction(self.menuKategorie.menuAction())
        self.menubar.addAction(self.menuRegeln.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        self.toolBar.addAction(self.actionRohdaten_laden)
        self.toolBar.addAction(self.actionExcel_exportieren)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRegelExcel_exportieren)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNeue_Regel)
        self.toolBar.addAction(self.actionNeue_Bedingung)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tarmed Paketmanager"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Infos"))
        self.groupBox.setTitle(_translate("MainWindow", "Kategorien"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Regeln"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.listView_regeln.setToolTip(_translate("MainWindow", "Definierte Regeln"))
        self.label_2.setText(_translate("MainWindow", "UND"))
        self.listView_regel_und.setToolTip(_translate("MainWindow", "Leistungen, die ALLE in einem Paket vorkommen müssen"))
        self.label_3.setText(_translate("MainWindow", "ODER"))
        self.listView_regeln_oder.setToolTip(_translate("MainWindow", "Leistungen, von denen EINE in einem Paket vorkommen muss"))
        self.label_4.setText(_translate("MainWindow", "NICHT"))
        self.listView_regeln_nicht.setToolTip(_translate("MainWindow", "Leistungen, von denen KEINE in einem Paket vorkommen darf"))
        self.menuRohdaten_laden.setTitle(_translate("MainWindow", "&Datei"))
        self.menuRegeln.setTitle(_translate("MainWindow", "&Regeln"))
        self.menuHilfe.setTitle(_translate("MainWindow", "&Hilfe"))
        self.menuKategorie.setTitle(_translate("MainWindow", "&Kategorien"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNeue_Kategorie.setText(_translate("MainWindow", "Neue Kategorie"))
        self.actionRohdaten_laden.setText(_translate("MainWindow", "&Rohdaten laden"))
        self.actionExcel_exportieren.setText(_translate("MainWindow", "Excel &exportieren"))
        self.actionNeue_Regel.setText(_translate("MainWindow", "&Neue Regel"))
        self.actionRegeln_speichern.setText(_translate("MainWindow", "Regeln &speichern"))
        self.actionRegel_laden.setText(_translate("MainWindow", "Regeln &laden"))
        self.actionKategorien_l_schen.setText(_translate("MainWindow", "Kategorien löschen"))
        self.actionRegelExcel_exportieren.setText(_translate("MainWindow", "Excel &exportieren"))
        self.actionRegelExcel_exportieren.setToolTip(_translate("MainWindow", "Excel mit Regeln exportieren"))
        self.action_Exit.setText(_translate("MainWindow", "E&xit"))
        self.action_uber.setText(_translate("MainWindow", "Über"))
        self.actionNeue_Bedingung.setText(_translate("MainWindow", "Neue Bedingung"))
        self.actionNeue_Bedingung.setToolTip(_translate("MainWindow", "Neue Bedingung für die aktuelle Regel"))
        self.actionRegeln_loeschen.setText(_translate("MainWindow", "Regeln löschen"))

import icons_rc
